### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by dgomes** [larsimmisch/pyalsaaudio#59] opened 2018-04-30 21:52 UTC
OS: Raspbian (Debian Stretch) - ALL packages updated
Kernel: Linux 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux
Using bluealsa 1.2.0
Using pyalsaaudio 0.8.4 (also happens with master branch)

Happens in both python2 and python3 with pyalsaaudio installed through PIP

```bash
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170124] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import alsaaudio
>>> alsaaudio.mixers(device="bluealsa")
Segmentation fault (core dumped)
```

GDB information:

Core was generated by `python3.5'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  alsamixer_list (self=<optimized out>, args=<optimized out>, kwds=<optimized out>) at alsaaudio.c:1168
1168	alsaaudio.c: No such file or directory.

The bug is related to the "device" argument, as it doesn't segfault with `alsaaudio.mixers()`

Before upgrading all packages (in months), no segmentation fault happened.

**Comment by dgomes** [comment] 2018-05-01 12:41
I was able to overcome this issue by disabling profiles in **bluealsa** daemon:

`bluealsa --disable-hsp --disable-hfp`

**Comment by dgomes** [comment] 2018-10-21 10:31
This issue still exists.

For future reference, bluealsa has changed interface. You now need to start with:

`bluealsa -p a2dp-source -p a2dp-sink`

**Comment by larsimmisch** [comment] 2020-07-16 21:58
I can't reproduce this, closing

**Closed by larsimmisch** 2020-07-16 21:58 UTC
